#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)

INVALIDOPT=0
COPYONLY=0
CONFIG=RELEASE
CONFIGLOWER=release
OUTDIR=
TEST=0

while getopts "cdo:t" opt; do
  case $opt in
    c)
      COPYONLY=1
      ;;
    d)
      CONFIG=DEBUG
      CONFIGLOWER=debug
      ;;
    o)
      OUTDIR=$OPTARG
      ;;
    t)
      TEST=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      INVALIDOPT=1
      ;;
  esac
done
shift $((OPTIND - 1)) 

if [ $INVALIDOPT -ne 0 ]; then
  exit 1
fi

if [[ "$1" != "" ]]; then
  echo "Invalid options: $*"
  exit 1
fi

cd $APPDIR

if [ $COPYONLY -ne 1 ]; then
  echo Cleaning
  stack clean
  if [ $? -ne 0 ]; then
    echo Clean failed
    exit 1
  fi

  echo Building
  stack build --ghc-options="-D$CONFIG"
  if [ $? -ne 0 ]; then
    echo Build failed
    exit 1
  fi

  echo Generating
  stack exec site rebuild
  if [ $? -ne 0 ]; then
    echo Generation failed
    exit 1
  fi

  if [ $TEST -eq 1 ]; then
    echo Testing
    diff -r _site_$CONFIGLOWER _site
    if [ $? -ne 0 ]; then
      echo Test failed
      exit 1
    fi
  fi
fi

if [[ "$OUTDIR" != "" ]]; then
  echo Deploying
  rm -rf $OUTDIR/* && cp -r _site/* $OUTDIR/
  if [ $? -ne 0 ]; then
    echo Deploy failed
    exit 1
  fi
fi
