#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)
OUTDIR=/var/www/rcook/seattlehaskell.local

cd $APPDIR
rm -rf $OUTDIR/* && \
  cp -r _site/* $OUTDIR
