#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)

if [[ "$OUTDIR" == "" ]]; then
  echo Must set OUTDIR
  exit 1
fi

cd $APPDIR
rm -rf $OUTDIR/* && \
  cp -r _site/* $OUTDIR
