#!/bin/bash
#!/bin/bash
set -e
if [[ "$OSTYPE" =~ ^darwin ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
THISPATH=$($READLINK -f $0)
THISDIR=$(dirname $THISPATH)
PROJECTDIR=$(dirname $THISDIR)

cd $PROJECTDIR
git submodule init && \
  git submodule update --recursive && \
  stack setup && \
  stack build
