#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)

cd $APPDIR
git submodule init && \
  git submodule update --recursive && \
  stack setup && \
  stack build
