#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)
OUTDIR=/var/www/rcook/seattlehaskell.local

cd $APPDIR
stack exec site rebuild && \
  diff -r _site_test/ _site/
