#!/bin/bash
set -e
if [[ "$OSTYPE" =~ ^darwin ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
THISPATH=$($READLINK -f $0)
THISDIR=$(dirname $THISPATH)
PROJECTDIR=$(dirname $THISDIR)

cd $PROJECTDIR

git rm -rf _site_debug/
rm -rf _site/
script/build -d
mv _site _site_debug
git add --all _site_debug/

git rm -rf _site_release/
rm -rf _site/
script/build
mv _site _site_release
git add --all _site_release/
