#!/bin/bash
set -e
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)

cd $APPDIR

git rm -rf _site_debug/
rm -rf _site/
script/build -d
mv _site _site_debug
git add --all _site_debug/

git rm -rf _site_release/
rm -rf _site/
script/build
mv _site _site_release
git add --all _site_release/
